---
- name: CouchDB Configuration
  hosts: slave
  tasks:
  - name: Installing docker
    command: yum install docker -y && service docker start
    ignore_errors: no

  - name: Getting couchdb image
    shell: service docker restart ; docker pull couchdb 

  - name: Creating container for the couchdb
    command: docker run --name DSR-couchdb11 -itd -p 8082:5984 couchdb:latest /bin/bash

